md <- masterdata2 %>%
select(Imagine you are the person in charge of the city budget. You have a total of $100 to allocate across various items to create a safe, healthy, and thriving community, listed below. The more money you allocate to an item, the higher priority it will have in your budget. Please allocate the $100 budget by entering the amount you wish to assign to each item in the respective boxes. The tally below will keep track of your total budget allocation. >> Long-term housing for all >> Dollar Amount) %>%
rename(Long-term housing for all = Imagine you are the person in charge of the city budget. You have a total of $100 to allocate across various items to create a safe, healthy, and thriving community, listed below. The more money you allocate to an item, the higher priority it will have in your budget. Please allocate the $100 budget by entering the amount you wish to assign to each item in the respective boxes. The tally below will keep track of your total budget allocation. >> Long-term housing for all >> Dollar Amount)
md <- masterdata2 %>%
  select("Imagine you are the person in charge of the city budget. You have a total of $100 to allocate across various items to create a safe, healthy, and thriving community, listed below. The more money you allocate to an item, the higher priority it will have in your budget. Please allocate the $100 budget by entering the amount you wish to assign to each item in the respective boxes. The tally below will keep track of your total budget allocation. >> Long-term housing for all >> Dollar Amount") %>%
  rename("Long-term housing for all" = "Imagine you are the person in charge of the city budget. You have a total of $100 to allocate across various items to create a safe, healthy, and thriving community, listed below. The more money you allocate to an item, the higher priority it will have in your budget. Please allocate the $100 budget by entering the amount you wish to assign to each item in the respective boxes. The tally below will keep track of your total budget allocation. >> Long-term housing for all >> Dollar Amount")
md <- masterdata2 %>%
select("How effective do you think police are at the following... >> Keeping your community safe")  %>%
rename("police_effect" = "How effective do you think police are at the following... >> Keeping your community safe")  
names(md)[names(md) == "Imagine you are the person in charge of the city budget. You have a total of $100 to allocate across various items to create a safe, healthy, and thriving community, listed below. The more money you allocate to an item, the higher priority it will have in your budget. Please allocate the $100 budget by entering the amount you wish to assign to each item in the respective boxes. The tally below will keep track of your total budget allocation. >> Long-term housing for all >> Dollar Amount"] <- "all_house"
names(masterdata2)[names(masterdata2) == "How effective do you think police are at the following... >> Keeping your community safe"] <- "police_effect"
names(masterdata2)[names(masterdata2) == "How effective do you think police are at the following... >> Preventing crime"] <- "police_crime"
names(masterdata2)[names(masterdata2) == "How effective do you think police are at the following... >> Preventing violence"] <- "police_vio"
names(masterdata2)[names(masterdata2) == "How effective do you think police are at the following... >> Responding to emergencies and disasters"] <- "police_respond"
write.csv(masterdata_edit, file = masterdata2.csv)
write.csv(masterdata2, file = "masterdata2.csv
names(masterdata2edit)[names(masterdata2edit) == "Imagine you are the person in charge of the city budget. You have a total of $100 to allocate across various items to create a safe, healthy, and thriving community, listed below. The more money you allocate to an item, the higher priority it will have in your budget. Please allocate the $100 budget by entering the amount you wish to assign to each item in the respective boxes. The tally below will keep track of your total budget allocation. >> Long-term housing for all >> Dollar Amount"] <-"all_house"
names(masterdata2edit)[names(masterdata2edit) == "Imagine you are the person in charge of the city budget. You have a total of $100 to allocate across various items to create a safe, healthy, and thriving community, listed below. The more money you allocate to an item, the higher priority it will have in your budget. Please allocate the $100 budget by entering the amount you wish to assign to each item in the respective boxes. The tally below will keep track of your total budget allocation. >> Healthy food and hunger prevention services >> Dollar Amount"] <-"all_food"
names(masterdata2edit)[names(masterdata2edit) == "Imagine you are the person in charge of the city budget. You have a total of $100 to allocate across various items to create a safe, healthy, and thriving community, listed below. The more money you allocate to an item, the higher priority it will have in your budget. Please allocate the $100 budget by entering the amount you wish to assign to each item in the respective boxes. The tally below will keep track of your total budget allocation. >> Quality healthcare (physical and mental healthcare) for all >> Dollar Amount"] <-"all_health"
names(masterdata2edit)[names(masterdata2edit) == "Imagine you are the person in charge of the city budget. You have a total of $100 to allocate across various items to create a safe, healthy, and thriving community, listed below. The more money you allocate to an item, the higher priority it will have in your budget. Please allocate the $100 budget by entering the amount you wish to assign to each item in the respective boxes. The tally below will keep track of your total budget allocation. >> Living wage jobs for all >> Dollar Amount"] <-"all_wage"

